# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=1)),
                ('view_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
