# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_viewtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtemplate',
            name='description',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 14, 46, 19, 652442, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
