# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20160604_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_num',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='std_code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
