# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20160610_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
